### ISSUE TITLE
loudest volume problem

### ISSUE THREAD

**Issue by gherbetto** [jenius-apps/ambie#407] opened 2023-12-08 00:33 UTC
Hello, great app you got here, there is an issue i noticed though. Whenever i launch an app no matter what volume of the sliders was set previously e.g. 20% or 100% the volume of the initial sound when you hit play is insanely LOUD. like 1000%.

Temporary fix for it is:
I have to move all of the sliders at least once for example if it was at 100% i move it 1% lower and the volume becomes normal even at 100% not comparable to what it sounded at the launch of the app.

Let me know if i can help by providing you with more information or to demonstrate it.

**Comment by dpaulino** [comment] 2023-12-08 08:21
I think I found the problem. Deploying a fix asap

**Comment by gherbetto** [comment] 2023-12-08 13:07
Oh thank you! I just finished recording just in case.On Dec 8, 2023, at 13:21, Daniel ***@***.***> wrote:﻿
I think I found the problem. Deploying a fix asap

**Comment by gherbetto** [comment] 2023-12-08 13:08
Oh thank you! I just finished recording just in case. 🙏

**Comment by dpaulino** [comment] 2023-12-08 16:54
I believe the issue is fixed. Can you try updating to 4.0.21 and let me know?

**Comment by gherbetto** [comment] 2023-12-09 07:02
Thank you. Sounds great!
But I'm unable to locate that version. In releases there is only 4.0.19

**Comment by dpaulino** [comment] 2023-12-09 17:00
ah, sorry about that. Try this: https://github.com/jenius-apps/ambie/releases/tag/v4.0.21

**Comment by dpaulino** [comment] 2023-12-09 22:55
Closing for now. I'll reopen if the issue is still there.

**Closed by dpaulino** 2023-12-09 22:55 UTC

**Comment by gherbetto** [comment] 2023-12-10 04:27
Wow, you found the solution almost immediately. It's working perfectly now. No more ear abuse) 🙏😊

**Comment by dpaulino** [comment] 2023-12-10 06:50
Glad to hear, thank you for confirming!
